# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-agency

url    : "https://www.scion.foundation" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : SCION Foundation
email      : info@scion.foundation # this is also the email contact forms will go to, if email based URL is used instead of ID based
description: "The SCION Foundation promotes the advancement of next generation internet"
author     : Nicola Rustignoli
logo:     #optional, defaults to site title
  path: \assets\img\logo_inverted.png
  height: 90 #height in px, defaults to 52px

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

include:
  - _pages

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/moqyewvd"
